name: Build NAPI Cross-Platform

on:
  push:
    branches: [main]
    paths:
      - 'runtimes/napi-bridge/**'
  pull_request:
    branches: [main]
    paths:
      - 'runtimes/napi-bridge/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: x86_64-apple-darwin
            build: |
              cd runtimes/napi-bridge
              pnpm build --target x86_64-apple-darwin
              strip -x *.node
          - host: macos-latest
            target: aarch64-apple-darwin
            build: |
              cd runtimes/napi-bridge
              pnpm build --target aarch64-apple-darwin
              strip -x *.node
          - host: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian
            build: |
              cd runtimes/napi-bridge
              pnpm build --target x86_64-unknown-linux-gnu
              strip *.node
          - host: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            docker: ghcr.io/napi-rs/napi-rs/nodejs-rust:lts-debian-aarch64
            build: |
              cd runtimes/napi-bridge
              pnpm build --target aarch64-unknown-linux-gnu
              aarch64-linux-gnu-strip *.node
          - host: windows-latest
            target: x86_64-pc-windows-msvc
            build: |
              cd runtimes/napi-bridge
              pnpm build --target x86_64-pc-windows-msvc
    name: stable - ${{ matrix.settings.target }} - node@18
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
      - name: Install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.settings.target }}
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            .cargo-cache
            target/
          key: ${{ matrix.settings.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: goto-bus-stop/setup-zig@v2
        if: ${{ matrix.settings.target == 'armv7-unknown-linux-gnueabihf' }}
        with:
          version: 0.10.1
      - name: Setup toolchain
        run: ${{ matrix.settings.setup }}
        if: ${{ matrix.settings.setup }}
        shell: bash
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build in docker
        uses: addnab/docker-run-action@v3
        if: ${{ matrix.settings.docker }}
        with:
          image: ${{ matrix.settings.docker }}
          options: '--user 0:0 -v ${{ github.workspace }}/.cargo-cache:/root/.cargo/registry/cache -v ${{ github.workspace }}/.cargo/registry/index:/root/.cargo/registry/index -v ${{ github.workspace }}:/build -w /build'
          run: ${{ matrix.settings.build }}
      - name: Build
        run: ${{ matrix.settings.build }}
        if: ${{ !matrix.settings.docker }}
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.settings.target }}
          path: runtimes/napi-bridge/*.node
          if-no-files-found: error

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Move artifacts to platform directories
        run: |
          cd runtimes/napi-bridge
          # Copy binaries to their platform-specific npm directories
          for artifact in ../../artifacts/bindings-*/; do
            if [ -d "$artifact" ]; then
              platform=$(basename "$artifact" | sed 's/bindings-//')
              case $platform in
                "x86_64-pc-windows-msvc")
                  cp "$artifact"/*.node npm/win32-x64-msvc/ || true
                  ;;
                "x86_64-apple-darwin")
                  cp "$artifact"/*.node npm/darwin-x64/ || true
                  ;;
                "aarch64-apple-darwin")
                  cp "$artifact"/*.node npm/darwin-arm64/ || true
                  ;;
                "x86_64-unknown-linux-gnu")
                  cp "$artifact"/*.node npm/linux-x64-gnu/ || true
                  ;;
                "aarch64-unknown-linux-gnu")
                  cp "$artifact"/*.node npm/linux-arm64-gnu/ || true
                  ;;
              esac
            fi
          done
          ls -la npm/*/*.node
      - name: Publish platform packages
        run: |
          cd runtimes/napi-bridge
          # Publish each platform package
          for platform_dir in npm/*/; do
            if [ -d "$platform_dir" ] && [ -f "$platform_dir/package.json" ]; then
              echo "Publishing $(basename $platform_dir)..."
              (cd "$platform_dir" && npm publish --access public) || echo "Failed to publish $(basename $platform_dir)"
            fi
          done
      - name: Publish main package
        run: |
          cd runtimes/napi-bridge
          # Copy all binaries to root for backward compatibility
          cp npm/*/*.node . || true
          npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}